apiVersion: v1
kind: Secret
metadata:
  name: notification-hub-kafka-secret
  namespace: notification-hub
type: Opaque
stringData:
  KAFKA_SASL_SERVER_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="CHANGE_ME" password="CHANGE_ME" user_CHANGE_ME="CHANGE_ME";
  KAFKA_SASL_SERVER_JAAS_CONFIG_FILE: |
    KafkaServer {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="CHANGE_ME"
      password="CHANGE_ME"
      user_CHANGE_ME="CHANGE_ME";
    };
  KAFKA_SSL_KEY_CREDENTIALS: CHANGE_ME_KEY_PASSWORD
  KAFKA_SSL_KEYSTORE_CREDENTIALS: CHANGE_ME_KEYSTORE_PASSWORD
  KAFKA_SSL_TRUSTSTORE_CREDENTIALS: CHANGE_ME_TRUSTSTORE_PASSWORD
  KAFKA_SSL_KEYSTORE_FILE: CHANGE_ME_PKCS12_KEYSTORE_FILE
  KAFKA_SSL_TRUSTSTORE_FILE: CHANGE_ME_PKCS12_TRUSTSTORE_FILE
