apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: notification-hub
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS notification_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS user_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE DATABASE IF NOT EXISTS delivery_service CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    GRANT ALL PRIVILEGES ON notification_service.* TO 'nhub'@'%';
    GRANT ALL PRIVILEGES ON user_service.* TO 'nhub'@'%';
    GRANT ALL PRIVILEGES ON delivery_service.* TO 'nhub'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: notification-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root1234"
            - name: MYSQL_USER
              value: "nhub"
            - name: MYSQL_PASSWORD
              value: "nhub1234"
            - name: MYSQL_DATABASE
              value: "notification_hub"
          ports:
            - containerPort: 3306
          args:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: notification-hub
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
