apiVersion: v1
kind: Secret
metadata:
  name: notification-hub-secret
  namespace: notification-hub
type: Opaque
stringData:
  MYSQL_USERNAME: nhub
  MYSQL_PASSWORD: nhub1234
  MONGODB_USERNAME: nhub
  MONGODB_PASSWORD: nhub1234
  JWT_SECRET: bm90aWZpY2F0aW9uaHViLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5n
