apiVersion: v1
kind: Secret
metadata:
  name: notification-hub-secret
  namespace: notification-hub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_USERNAME: CHANGE_ME
  MYSQL_PASSWORD: CHANGE_ME
  MONGODB_USERNAME: CHANGE_ME
  MONGODB_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_BASE64_32_BYTE_MIN
