apiVersion: v1
kind: Secret
metadata:
  name: notification-hub-secret
  namespace: notification-hub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_USERNAME: CHANGE_ME
  MYSQL_PASSWORD: CHANGE_ME
  MONGODB_USERNAME: CHANGE_ME
  MONGODB_PASSWORD: CHANGE_ME
  ACTUATOR_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME_BASE64_32_BYTE_MIN
  KAFKA_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="CHANGE_ME" password="CHANGE_ME";
  KAFKA_SASL_SERVER_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="CHANGE_ME" password="CHANGE_ME";
  KAFKA_SSL_TRUSTSTORE_CERTIFICATES: CHANGE_ME_PEM_CA_CERTIFICATE
  KAFKA_SSL_KEYSTORE_CERTIFICATE_CHAIN: CHANGE_ME_PEM_SERVER_CERTIFICATE
  KAFKA_SSL_KEYSTORE_KEY: CHANGE_ME_PEM_SERVER_PRIVATE_KEY
