server:
  port: 8084

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      uri: mongodb://nhub:nhub1234@localhost:27017/analytics?authSource=admin
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

jwt:
  secret: bm90aWZpY2F0aW9uaHViLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5n
  access-token-expire-ms: 3600000
  refresh-token-expire-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
